// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using senai.spacekids.repository.Context;
using System;

namespace senai.spacekids.repository.Migrations
{
    [DbContext(typeof(SpaceKidsContext))]
    [Migration("20180308005900_spacekids")]
    partial class spacekids
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("senai.spacekids.domain.Entities.Crianca", b =>
                {
                    b.Property<int>("CriancaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("foto");

                    b.Property<int>("idade");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("paiId");

                    b.Property<string>("sexo")
                        .IsRequired();

                    b.HasKey("CriancaId");

                    b.HasIndex("paiId");

                    b.ToTable("Criancas");
                });

            modelBuilder.Entity("senai.spacekids.domain.Entities.Desempenho", b =>
                {
                    b.Property<int>("desempenhoId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("acertou");

                    b.Property<int>("criancaId");

                    b.Property<int>("faseId");

                    b.Property<DateTime>("horaFinal");

                    b.Property<DateTime>("horaInicial");

                    b.HasKey("desempenhoId");

                    b.HasIndex("criancaId");

                    b.HasIndex("faseId");

                    b.ToTable("Desempenhos");
                });

            modelBuilder.Entity("senai.spacekids.domain.Entities.Fase", b =>
                {
                    b.Property<int>("FaseId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CriancaId");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("FaseId");

                    b.HasIndex("CriancaId");

                    b.ToTable("Fases");
                });

            modelBuilder.Entity("senai.spacekids.domain.Entities.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.HasKey("LoginId");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("senai.spacekids.domain.Entities.Pai", b =>
                {
                    b.Property<int>("paiId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LoginId");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("paiId");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("senai.spacekids.domain.Entities.Crianca", b =>
                {
                    b.HasOne("senai.spacekids.domain.Entities.Pai", "pai")
                        .WithMany("Criancas")
                        .HasForeignKey("paiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("senai.spacekids.domain.Entities.Desempenho", b =>
                {
                    b.HasOne("senai.spacekids.domain.Entities.Crianca", "Crianca")
                        .WithMany()
                        .HasForeignKey("criancaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("senai.spacekids.domain.Entities.Fase", "Fase")
                        .WithMany()
                        .HasForeignKey("faseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("senai.spacekids.domain.Entities.Fase", b =>
                {
                    b.HasOne("senai.spacekids.domain.Entities.Crianca")
                        .WithMany("Fases")
                        .HasForeignKey("CriancaId");
                });

            modelBuilder.Entity("senai.spacekids.domain.Entities.Pai", b =>
                {
                    b.HasOne("senai.spacekids.domain.Entities.Login", "Login")
                        .WithOne("Pai")
                        .HasForeignKey("senai.spacekids.domain.Entities.Pai", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
